# Generated by Django 5.2.4 on 2025-07-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='remember_token',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
